version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.4.1

parameters:
  ApiTrigger:
    type: boolean
    default: false
  notifyToSlack:
    type: boolean
    default: true


executors:
  docker-cypress:
    environment:
      TERM: xterm
    docker:
      - image: cypress/browsers:node14.16.0-chrome90-ff88

commands:
  #My custom command name 'install-browsers'
  install-browsers:
    description: "Checkout to my code and install browsers"
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  send-notification-to-slack-channel:
    description: "Send notification to Slack channel"
    steps:
      - when:
          condition: << pipeline.parameters.notifyToSlack >>
          steps:
            - slack/status:
                channel: C041TRUTE4V
                fail_only: false
                only_for_branches: master
                webhook: $SLACK_WEBHOOK

  run-automation-tests:
    description: "Run automation tests"
    steps:
      - run:
          name: Run automation tests
          command: npm run cy:run:all:tests:in:cloud

  upload-generated-mocha-report:
    description: "generating mocha report"
    steps:
      - store_artifacts:
          name: Upload Mocha report
          path: reporter-output

jobs:
  automation-tests-run:
    working_directory: ~/Cypress-Automation_tests
    executor: docker-cypress
    parallelism: 2
    steps:
      - install-browsers
      - restore-and-save-cache
      - run-automation-tests
      - send-notification-to-slack-channel

workflows:
  commit-workflow:
    when:
      and:
        - equal: [ false, << pipeline.parameters.ApiTrigger >>]
    jobs:
      - automation-tests-run:
          filters:
            branches:
               only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 5 * * 2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-run


  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - automation-tests-run