version: 2.1
orbs:
  slack: circleci/slack@3.4.2

parameters:
  ApiTrigger:
    type: boolean
    default: false
  notifyToSlack:
    type: boolean
    default: true
  NightlyRunNotify:
    type: boolean
    default: true


executors:
  docker-cypress:
    environment:
      TERM: xterm
    docker:
      - image: cypress/base:14

commands:
  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  run-automation-tests:
    description: "Run automation tests"
    steps:
      - run:
          name: Running tests
          command: npm run cypress:run

      - store_test_results:
          path: test-results


  send-notification-to-slack-channel:
    description: "Send notification to Slack channel"
    steps:
      - when:
          condition: << pipeline.parameters.notifyToSlack >>
          steps:
            - slack/status:
                channel: C041TRUTE4V
                fail_only: false
                only_for_branches: master
                webhook: $SLACK_WEBHOOK

  run-mocha-report:
    description: "run-mocha-report"
    steps:
      - run:
          name: Mocha report generation
          command: npm run cy:generate:mocha:report

  upload-generated-mocha-report:
    description: "generating-mocha-report"
    steps:
      - store_artifacts:
          name: Upload Mocha report
          path: reporter-output

jobs:
  automation-tests-running-configuration:
    working_directory: ~/Cypress-Automation_tests
    executor: docker-cypress
    parallelism: 1
    steps:
      - restore-and-save-cache
      - run-automation-tests
      - run-mocha-report
      - upload-generated-mocha-report
      - send-notification-to-slack-channel


workflows:
  commit-workflow:
    when:
      and:
        - equal: [ false, << pipeline.parameters.ApiTrigger >>]
    jobs:
      - automation-tests-running-configuration:
          filters:
            branches:
               only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 5 * * 2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-running-configuration:
          NightlyRunNotify: true

  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - automation-tests-running-configuration