version: 2.1
orbs:
  slack: circleci/slack@3.4.2

parameters:
  ApiTrigger:
    type: boolean
    default: false
  notifyToSlack:
    type: boolean
    default: true


executors:
  docker-cypress:
    environment:
      TERM: xterm
    docker:
      - image: cypress/base:14

commands:
  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  send-notification-to-slack-channel:
    description: "Send notification to Slack channel"
    steps:
      - when:
          condition: << pipeline.parameters.notifyToSlack >>
          steps:
            - slack/status:
                channel: C041TRUTE4V
                fail_only: false
                only_for_branches: master
                webhook: $SLACK_WEBHOOK

  cypress-clean-cypress-results-folder:
    description: "cypress-clean-cypress-results-folder"
    steps:
      - run:
          name: cypress-clean-cypress-results-folder
          command: npm run cypress:clean:cypress-results:folder

  cypress-clean-mochawesome-report-folder:
    description: "Clean mochawesome report folder"
    steps:
      - run:
          name: Clean-cypress-results-folder
          command: npm run cypress:clean:mochawesome-report:folder

  run-automation-tests-with-mocha-report:
    description: "Run automation tests with mocha report"
    steps:
      - run:
          name: Run automation tests with mocha report
          command: npm run cy:generate:mocha:report

  merge-mocha-report:
    description: "Merge mocha report"
    steps:
      - run:
          name: merge mocha report
          command: npm run cy:merge:mocha:report

  generate-mocha-report-folder:
    description: "Generate mocha report"
    steps:
      - run:
          name: generate-mocha-report-folde
          command: npm run cypress:generate:mocha:report

  upload-generated-mocha-report:
    description: "generating mocha report"
    steps:
      - store_artifacts:
          name: Upload Mocha report
          path: mochawesome-report

jobs:
  automation-tests-run:
    working_directory: ~/Cypress-Automation_tests
    executor: docker-cypress
    parallelism: 1
    steps:
      - restore-and-save-cache
      - cypress-clean-cypress-results-folder
      - cypress-clean-mochawesome-report-folder
      - run-automation-tests-with-mocha-report
      - merge-mocha-report
      - upload-generated-mocha-report
      - send-notification-to-slack-channel


workflows:
  commit-workflow:
    when:
      and:
        - equal: [ false, << pipeline.parameters.ApiTrigger >>]
    jobs:
      - automation-tests-run:
          filters:
            branches:
               only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 5 * * 2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-run


  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - automation-tests-run