version: 2.1

executors:
  docker-cypress:
    environment:
      TERM: xterm
    docker:
      - image: cypress/base:14

jobs:
  test:
    working_directory: ~/app
    executor: docker-cypress
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running tests
          command: npm run cypress:run
      - store_test_results:
          path: test-results


workflows:
  testing:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - feature/circle-ci
